kamathi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include('shop.urls')),
    path("accounts/", include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls'))
   ]

shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    HomeView,
    ProductDetailView, AnalyticalListView,
    ChromatographyListView,ClinicalListView,LaboratoryListView,
    MedicalListView,MicroscopesListView,
    ProcessListView,SemiConductorListView,
    SpectroscopyListView,TestMeasurementListView
)

app_name = 'shop'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>/', ProductDetailView.as_view(), name ="product"),
    path("analytical/", AnalyticalListView.as_view(), name="analytical"),
    path('chromatography/',ChromatographyListView.as_view(), name="chromatography"),
    path('clinical/',ClinicalListView.as_view(), name="clinical"),
    path('laboratory/',LaboratoryListView.as_view(), name="laboratory"),
    path('medical/',MedicalListView .as_view(), name="medical"),
    path('microscopes/',MicroscopesListView.as_view(), name="microscopes"),
    path('process/',ProcessListView.as_view(), name="process"),
    path('spectroscopy/',SpectroscopyListView.as_view(), name="spectroscopy"),
    path('semiconductor/',SemiConductorListView.as_view(), name="semiconductor"),
    path('testmeasurement/',TestMeasurementListView.as_view(), name="testmeasurement"),







    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.utils import timezone
from datetime import datetime 
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify


# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=150, verbose_name='Title')
    slug = models.SlugField(max_length=150, unique=True,
                            allow_unicode=True, blank=True, null=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        unique_together = (('title', 'slug'),)

    def get_absolute_url(self):
        return reverse('categories', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
LABEL = (
    ('New','New'),
    ('Refurb','Refurb')
    )

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='Category')
    label = models.CharField(max_length=10, choices=LABEL)
    product_details = RichTextUploadingField(blank=True, null=True)
    product_model = models.TextField(blank= True,max_length=30,  null=True)
    seller_information = models.TextField(blank= True, null=True)
    image = models.ImageField(upload_to='images',default=None, verbose_name='Thumbnail')
    product_images = models.ImageField(upload_to='images/%Y/%m/%d',blank=True, null=True)
    description = models.TextField()
    created_on = models.DateTimeField(default=datetime.now)
    slug = models.SlugField(default='test-product')
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product", kwargs={"slug": self.slug})
    def date_published(self):
        return self.created_on.strftime("%B %d, %Y %H:%M")
    
    
    
    

templates/store/analytical.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Spectroscopy Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/chromatography.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Chromatography Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/clinical.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Clinical Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/laboratory.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Laboratory Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/medical.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Medical Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/microscopes.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Microscopes Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/process.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Process Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/semiconductor.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Semi-Conductor Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}

templates/store/spectroscopy.html
{% extends "base.html" %} {% load static %} {% load widget_tweaks %} {% block content %}

<div>
    <div class="sidebar ">
        <a class="active " href="{% url 'shop:home' %}">Categories</a>
        <a href="{% url 'shop:analytical' %}">Analytical</a>
        <a href="{% url 'shop:chromatography' %}">Chromatography</a>
        <a href="{% url 'shop:clinical' %}">Clinical</a>
        <a href="{% url 'shop:laboratory' %}">Laboratory</a>
        <a href="{% url 'shop:medical' %}">Medical</a>
        <a href="{% url 'shop:microscopes' %}">Microscopes</a>
        <a href="{% url 'shop:process' %}">Process</a>
        <a href="{% url 'shop:semiconductor' %}">SemiConductor</a>
        <a href="{% url 'shop:spectroscopy' %}">Spectroscopy</a>
        <a href="{% url 'shop:testmeasurement' %}">Test & Measurement</a>
        <hr> {% if request.user %} {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %} " class="glyphicon glyphicon-log-out "> Logout</a> {% else %}
        <a href="{% url 'login' %} " class="glyphicon glyphicon-log-in "> login</a>
        <a href="{% url 'signup' %} " class="glyphicon glyphicon-registration-mark "> Signup</a> {% endif %} {% endif %}</a>

    </div>

    <!-- Page content -->
    <div class="content" style="left: 100px; ">

        <div class="container-sm ">
            <h4 class="page-header ">Spectroscopy Products & Solutions</h4> {% for product in product_list %}
            <div class="row-one">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> <img src="{{ product.image.url }}" class="card-img img-fluid" width="150" height="150" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h4 class="font-weight-semibold mb-2"> <a href="{{ product.get_absolute_url }}" class="text-default mb-2" data-abc="true">{{ product.name }}</a> </h4>
                            <a href="#" class="text-muted" data-abc="true">{{ product.category}}</a>
                        </div>
                        <h5 class="mb-0 font-weight-semibold">Ksh {% if product.discount_price %} {{product.discount_price|floatformat:2}} {% else %} {{product.price|floatformat:2}} {% endif %}</h5>
                        <div class="text-muted mb-3"></div><label class="label label-primary">{{ product.label }}</label></div>
                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
                </div>
            </div> {% endfor %}
        </div>

    </div>
</div>{%endblock%}